dj_panel_auto_dj:
    resource: "@DjPanelAutoDjBundle/Resources/config/routing.yml"
    prefix:   /

dj_panel_show:
    resource: "@DjPanelShowBundle/Resources/config/routing.yml"
    prefix:   /

dj_panel_user:
    resource: "@DjPanelUserBundle/Resources/config/routing.yml"
    prefix:   /

dj_panel_main:
    resource: "@DjPanelMainBundle/Resources/config/routing.yml"
    prefix:   /

dj_panel_api:
    resource: "@DjPanelApiBundle/Resources/config/routing.yml"
    prefix:   /api
    options:
        expose: true


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
